# permissions for end users to edit apolloportals.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apolloportal-editor-role
rules:
- apiGroups:
  - apollo.io
  resources:
  - apolloportals
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apollo.io
  resources:
  - apolloportals/status
  verbs:
  - get
