# permissions for end users to view apolloes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apollo-viewer-role
rules:
- apiGroups:
  - apollo.io
  resources:
  - apolloes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apollo.io
  resources:
  - apolloes/status
  verbs:
  - get
